const productos = [
  {
    id: 1,
    nombre: "Audífonos N4",
    precio: 120000,
    categoria: "N4",
    imagen: "/img/Airpors_2.png",
    descripcion: "Audífonos N4 con cancelación de ruido y buena batería.",
    imagenesExtra: ["/img/airpodsN4_2.png", "/img/airpodsN4_3.png"],
    metodosPago: ["Nequi", "Bancolombia", "Efectivo"],
  },
  {
    id: 2,
    nombre: "Audifonos N4",
    precio: 150000,
    categoria: "N4",
    imagen: "/img/Airpors_6.png",
    descripcion: "Bafle con gran potencia y sonido envolvente.",
    imagenesExtra: ["/img/bafle2.png", "/img/bafle3.png"],
    metodosPago: ["Nequi", "Tarjeta", "Contraentrega"],
  },
  {
    id: 3,
    nombre: "Bafles",
    precio: 150000,
    categoria: "Bafle",
    imagen: "/img/bafles_1.png",
    descripcion: "Bafle con gran potencia y sonido envolvente.",
    imagenesExtra: ["/img/bafle2.png", "/img/bafle3.png"],
    metodosPago: ["Nequi", "Tarjeta", "Contraentrega"],
  },
   {
    id: 4,
    nombre: "Bafles",
    precio: 150000,
    categoria: "Bafle",
    imagen: "/img/bafles_2.png",
    descripcion: "Bafle con gran potencia y sonido envolvente.",
    imagenesExtra: ["/img/bafle2.png", "/img/bafle3.png"],
    metodosPago: ["Nequi", "Tarjeta", "Contraentrega"],
  }, 
  {
    id: 5,
    nombre: "Audifonos",
    precio: 150000,
    categoria: "N5",
    imagen: "/img/audifonos_1.png",
    descripcion: "Bafle con gran potencia y sonido envolvente.",
    imagenesExtra: ["/img/bafle2.png", "/img/bafle3.png"],
    metodosPago: ["Nequi", "Tarjeta", "Contraentrega"],
  },
];

export default productos;
